"""empty message

Revision ID: 1ff97836c0dd
Revises: e16ddd7414e7
Create Date: 2021-03-30 21:24:21.557523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff97836c0dd'
down_revision = 'e16ddd7414e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'deleted_at')
    # ### end Alembic commands ###
