"""empty message

Revision ID: 8ddfedb5a5be
Revises: 12c4f05c2c68
Create Date: 2021-03-25 17:53:11.006354

"""
from alembic import op
import sqlalchemy as sa

from datetime import datetime


# revision identifiers, used by Alembic.
revision = '8ddfedb5a5be'
down_revision = '12c4f05c2c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, onupdate=datetime.now),
    sa.Column('updated_at', sa.DateTime(), nullable=True, onupdate=datetime.now),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
