"""empty message

Revision ID: cb316b6955ba
Revises: 8ddfedb5a5be
Create Date: 2021-03-27 12:49:02.652450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb316b6955ba'
down_revision = '8ddfedb5a5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('draft', sa.Boolean(), nullable=True))
    op.add_column('article', sa.Column('first_paragraph', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'first_paragraph')
    op.drop_column('article', 'draft')
    # ### end Alembic commands ###
